[platformio]
default_envs = nanoatmega328

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_speed = 115200
monitor_speed = 115200
; Uncomment and set your actual serial port before uploading, e.g.:
; upload_port = COM3
build_flags = -D F_CPU=16000000L
